server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10

ly:
  jwt:
    secret: ly@Login(Auth}*^31)&jcohao% # 登录校验密钥
    pubKeyPath: D:\rsa\rsa.pub # 公钥地址
    priKeyPath: D:\rsa\rsa.pri # 私钥地址
    expire: 30  # 过期时间，单位为分钟
    cookieMaxAge: 1800 # cookie 的过期时间
    cookieName: LY_TOKEN # cookie 的名称