server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5    # 每隔 5s 发一次心跳
    lease-expiration-duration-in-seconds: 10    # 超过 10s 不发送心跳则服务过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB    # 限制上传文件大小不超过 5 MB
#fdfs:
#  so-timeout: 1501
#  connect-timeout: 601
#  thumb-image:    # 略缩图规格
#    width: 60
#    height: 60
#  tracker-list:   # tracker 地址

