server:
  port: 8084

spring:
  application:
    name: goods-page
  thymeleaf:
    cache: false    # 关闭 thymeleaf 的缓存方便调试
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

ly:
  thymeleaf:
    destPath: G:/nginx-1.12.2/html/item