server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///leyou?serverTimezone=UTC
    username: root
    password: hao123456
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    template:   # 有关 AmqpTemplate 的配置
      retry:    # 失败重试
        enabled: true   # 开启失败重试
        initial-interval: 10000ms   # 第一次重试的间隔时长
        max-interval: 30000ms       # 最长重试间隔，超过此间隔则不再重试
        multiplier: 2               # 下次重试间隔的倍数，这里的 2 表示下次重试间隔是上次的 2 倍
      exchange: ly.item.exchange    # 默认交换机名称，发送消息时不指定交换机则会用此当默认值
    publisher-confirms: true        # 生产者确认机制，确保消息会正确发送，如果发送失败则会有错误回执，从而触发重试
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5    # 每隔 5s 发一次心跳
    lease-expiration-duration-in-seconds: 10    # 超过 10s 不发送心跳则服务过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}


